[package]
name = "defi-rust-cli"
version = "0.1.0"
edition = "2018"
authors = [
    "DeFi Blockchain Developers <engineering@defichain.com>"
]
description = "DeFichain RPC client"

[dependencies]
clap = { version = "2.33.3", features = ["yaml"] }